services:

  web-app:
    container_name: web-app
    build: ./dockerfiles
    volumes:
      - ./web-app:/var/www/html
      - ./core:/var/www/core
    ports:
      - "8000:80"
    environment:
      - ALLOW_OVERRIDE = true
      - PHP_IDE_CONFIG="serverName=web-app"

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "9002:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - "./.data/mysql:/var/lib/mysql"
    command: mysqld --sql-mode="" --max_connections=1000 --max_allowed_packet=325058560 --wait_timeout=28800 --interactive_timeout=28800 --user=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 10s
      start_period: 3s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "9001:80"
    environment:
      UPLOAD_LIMIT: 2G
      PMA_HOST: "mysql_db"
      PMA_USER: "root"
      PMA_PASSWORD: ""
      PMA_PORT: 3306
    depends_on:
      - mysql_db